### PR TITLE
enable working with percentiles

### PR DESCRIPTION
**Pull request by dulcineapena1**
Releted to #39 
Add the hability to work with percentiles attributes values.

### CODE REVIEW

**Comment by dulcineapena1** [comment]
Hello @glitton
Thanks for your answer. Unfortunately I could not replicate that error that you mention... I will appreciate if you could tell me more about where did you get the error...

Talking about the explanation that you ask me, I notice when I try to work with percentiles, I got a blank cell instead of the bullet or the value. For example if I select an event type SystemSample, attribute median(cpuSystemPercent), I will have a blank cell in my board; and in case I add a comparison less than 1, my entire board will crash with the message 'Oops! Something went wrong.' I mean, I would expect to have a bullet in my board, similar that the ones you get when you are working with another type of attribute. 
I don't know if there is a good thing to have this, or maybe Neon board is not supposed to work with percentiles. 

Thanks for your time!

**Comment by danielgolden** [comment]
@glitton Any thoughts on @dulcineapena1's latest comment?

**Comment by jpvajda** [comment]
This seems like a stale PR, so I'll close unless someone can confirm this is still being worked on.

**Comment by dulcineapena1** [comment]
> This seems like a stale PR, so I'll close unless someone can confirm this is still being worked on.
@jpvajda 
You can close this PR, I was working on it few months ago, but I am not longer on it because I couldn't find the requested error... I thought this could be a usefull functionality but maybe this is not that is completely necesary for now. 
Thank you.

**Comment by jpvajda** [comment]
@dulcineapena1 ok thanks for confirming.

**Pull request closed without merging**
